name: YouTube Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test automation
        run: echo "YouTube automation system is working!"
